### ISSUE TITLE
In Delphi 10.3 - 64bits QRcode is empty

### ISSUE THREAD

**Issue by gosanefr** [landrix/Zint-Barcode-Generator-for-Delphi#16]
Take VCL-QR-EPC demo, add platform Win64 and run : the QRcode shows an empty content.

**Comment by landrix** [comment]
It works for me. Have you ever tried to save the picture to a file?

**Comment by gosanefr** [comment]
No, I just scan the generated qrCode displayed by the application with my phone :
![image](https://user-images.githubusercontent.com/11263545/92575822-12ea2e80-f289-11ea-849a-92405c568654.png)

**Comment by gosanefr** [comment]
This picture was from Win64 code. Here is the corresponding QRcode (same data) compiled in 32bits :
![image](https://user-images.githubusercontent.com/11263545/92589854-7da46580-f29b-11ea-9d87-508c5f1ffba7.png)
I don't see a "display" problem : the image *is* a QRcode but it just contains no data.

**Comment by landrix** [comment]
Yes, win64 = win32

![image](https://user-images.githubusercontent.com/3299479/92590355-5dc17180-f29c-11ea-85d5-8ff3b45a8989.png)

**Comment by gosanefr** [comment]
When I scan your screenshot it says "0 characters". I have tried saving your image and uploaded it here : https://zxing.org/w/decode.jspx with the same result ("No barcode was found in this image. Either it did not contain a barcode, or did not contain one in a supported format, or the software was simply unable to find it. Go "Back" in your browser and try another image.")

**Comment by gosanefr** [comment]
Same on this site : https://blog.qr4.nl/Online-QR-Code-Decoder.aspx

**Comment by landrix** [comment]
Sorry, you are right. Win64 produces a different image. I will investigate on this, when i have time.

**Comment by landrix** [comment]
Can you check the current release?

https://github.com/landrix/Zint-Barcode-Generator-for-Delphi/commit/cd3207e8910c197396c1f9c3757f9287e9dc9275

**Comment by gosanefr** [comment]
It works perfectly now ! Thanks for the very quick fix.
