### ISSUE TITLE
Compiler warining

### ISSUE THREAD

**Issue by hafedh-trimeche** [landrix/Zint-Barcode-Generator-for-Delphi#2]
Please note these warnings:
[dcc32 Hint] zint_helper.pas(93): H2164 Variable 'i' is declared but never used in 'ArrayOfCharToArrayOfByte'
[dcc32 Hint] zint_common.pas(411): H2077 Value assigned to 'output' never used
[dcc32 Hint] zint_common.pas(411): H2077 Value assigned to 'fraction' never used
[dcc32 Warning] zint_reedsol.pas(176): W1024 Combining signed and unsigned types - widened both operands
[dcc32 Hint] zint_dmatrix.pas(525): H2077 Value assigned to 'best_count' never used
[dcc32 Hint] zint_dmatrix.pas(485): H2077 Value assigned to 'done' never used
[dcc32 Hint] zint_gs1.pas(277): H2077 Value assigned to 'last_ai' never used
[dcc32 Hint] zint_code128.pas(197): H2077 Value assigned to 'current' never used
[dcc32 Hint] zint_code128.pas(533): H2077 Value assigned to 'last_set' never used
[dcc32 Hint] zint_2of5.pas(60): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_2of5.pas(99): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_2of5.pas(135): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_2of5.pas(171): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_2of5.pas(209): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_2of5.pas(273): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_2of5.pas(324): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_2of5.pas(379): H2077 Value assigned to 'dpident' never used
[dcc32 Warning] zint_aztec.pas(1206): W1036 Variable 'codeword_size' might not have been initialized
[dcc32 Warning] zint_aztec.pas(1266): W1036 Variable 'compact' might not have been initialized
[dcc32 Hint] zint_aztec.pas(1574): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_qr.pas(435): H2077 Value assigned to 'second' never used
[dcc32 Hint] zint_qr.pas(434): H2077 Value assigned to 'first' never used
[dcc32 Hint] zint_qr.pas(547): H2077 Value assigned to 'third' never used
[dcc32 Hint] zint_qr.pas(546): H2077 Value assigned to 'second' never used
[dcc32 Hint] zint_qr.pas(545): H2077 Value assigned to 'first' never used
[dcc32 Hint] zint_qr.pas(325): H2164 Variable 'j' is declared but never used in 'qr_binary'
[dcc32 Hint] zint_qr.pas(1498): H2077 Value assigned to 'second' never used
[dcc32 Hint] zint_qr.pas(1497): H2077 Value assigned to 'first' never used
[dcc32 Hint] zint_qr.pas(1544): H2077 Value assigned to 'third' never used
[dcc32 Hint] zint_qr.pas(1543): H2077 Value assigned to 'second' never used
[dcc32 Hint] zint_qr.pas(1542): H2077 Value assigned to 'first' never used
[dcc32 Warning] zint_qr.pas(1863): W1036 Variable 'ecc_codewords' might not have been initialized
[dcc32 Warning] zint_qr.pas(1848): W1036 Variable 'data_codewords' might not have been initialized
[dcc32 Warning] zint_qr.pas(1816): W1036 Variable 'bits_total' might not have been initialized
[dcc32 Warning] zint_qr.pas(1970): W1036 Variable 'ecc_codewords' might not have been initialized
[dcc32 Warning] zint_qr.pas(1889): W1036 Variable 'bits_total' might not have been initialized
[dcc32 Warning] zint_qr.pas(1937): W1036 Variable 'data_codewords' might not have been initialized
[dcc32 Warning] zint_qr.pas(2049): W1036 Variable 'ecc_codewords' might not have been initialized
[dcc32 Warning] zint_qr.pas(2034): W1036 Variable 'data_codewords' might not have been initialized
[dcc32 Warning] zint_qr.pas(1999): W1036 Variable 'bits_total' might not have been initialized
[dcc32 Warning] zint_upcean.pas(280): W1023 Comparing signed and unsigned types - widened both operands
[dcc32 Warning] zint_upcean.pas(382): W1024 Combining signed and unsigned types - widened both operands
[dcc32 Warning] zint_upcean.pas(403): W1024 Combining signed and unsigned types - widened both operands
[dcc32 Warning] zint_upcean.pas(688): W1023 Comparing signed and unsigned types - widened both operands
[dcc32 Warning] zint_maxicode.pas(695): W1024 Combining signed and unsigned types - widened both operands
[dcc32 Hint] zint_maxicode.pas(712): H2077 Value assigned to 'service' never used
[dcc32 Hint] zint_maxicode.pas(712): H2077 Value assigned to 'countrycode' never used
[dcc32 Hint] zint_maxicode.pas(703): H2164 Variable 'error_number' is declared but never used in 'maxicode'
[dcc32 Hint] zint_code.pas(100): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_code.pas(185): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_code.pas(295): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_code.pas(346): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_code.pas(564): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_medical.pas(63): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_medical.pas(172): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_medical.pas(224): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_medical.pas(319): H2077 Value assigned to 'checkpart' never used
[dcc32 Hint] zint_code16k.pas(162): H2077 Value assigned to 'current' never used
[dcc32 Hint] zint_pdf417.pas(596): H2077 Value assigned to 'codeascii' never used
[dcc32 Warning] zint_pdf417.pas(807): W1073 Combining signed type and unsigned 64-bit type - treated as an unsigned type
[dcc32 Hint] zint_pdf417.pas(762): H2077 Value assigned to 'total' never used
[dcc32 Hint] zint_pdf417.pas(761): H2077 Value assigned to 'mantisa' never used
[dcc32 Hint] zint_pdf417.pas(760): H2077 Value assigned to 'chunkLen' never used
[dcc32 Hint] zint_pdf417.pas(1035): H2077 Value assigned to 'total' never used
[dcc32 Hint] zint_pdf417.pas(1389): H2077 Value assigned to 'total' never used
[dcc32 Hint] zint_large.pas(104): H2077 Value assigned to 'done' never used
[dcc32 Hint] zint_rss.pas(678): H2077 Value assigned to 'check_digit' never used
[dcc32 Hint] zint_rss.pas(364): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_rss.pas(1250): H2077 Value assigned to 'check_digit' never used
[dcc32 Hint] zint_rss.pas(953): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_rss.pas(1426): H2077 Value assigned to 'value' never used
[dcc32 Hint] zint_rss.pas(1420): H2077 Value assigned to 'last_mode' never used
[dcc32 Warning] zint_rss.pas(2444): W1036 Variable 'c_group' might not have been initialized
[dcc32 Hint] zint_composite.pas(245): H2077 Value assigned to 'total' never used
[dcc32 Hint] zint_composite.pas(489): H2077 Value assigned to 'total' never used
[dcc32 Hint] zint_composite.pas(694): H2077 Value assigned to 'total' never used
[dcc32 Hint] zint_composite.pas(1791): H2077 Value assigned to 'alpha_pad' never used
[dcc32 Hint] zint_composite.pas(1611): H2077 Value assigned to 'd1' never used
[dcc32 Hint] zint_composite.pas(1610): H2077 Value assigned to 'd1' never used
[dcc32 Hint] zint_composite.pas(1815): H2077 Value assigned to 'n' never used
[dcc32 Hint] zint_composite.pas(1867): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_gridmtx.pas(469): H2077 Value assigned to 'best_count' never used
[dcc32 Hint] zint_gridmtx.pas(535): H2077 Value assigned to 'last_mode' never used
[dcc32 Warning] zint_gridmtx.pas(1124): W1023 Comparing signed and unsigned types - widened both operands
[dcc32 Warning] zint_plessey.pas(84): W1024 Combining signed and unsigned types - widened both operands
[dcc32 Warning] zint_plessey.pas(84): W1024 Combining signed and unsigned types - widened both operands
[dcc32 Warning] zint_plessey.pas(89): W1024 Combining signed and unsigned types - widened both operands
[dcc32 Hint] zint_plessey.pas(48): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_code1.pas(291): H2077 Value assigned to 'best_count' never used
[dcc32 Hint] zint_code1.pas(311): H2077 Value assigned to 'done' never used
[dcc32 Hint] zint_code1.pas(761): H2077 Value assigned to 'latch' never used
[dcc32 Hint] zint_code1.pas(652): H2077 Value assigned to 'latch' never used
[dcc32 Hint] zint_code1.pas(541): H2077 Value assigned to 'latch' never used
[dcc32 Hint] zint_code1.pas(370): H2077 Value assigned to 'latch' never used
[dcc32 Warning] zint_code1.pas(1694): W1036 Variable 'sub_version' might not have been initialized
[dcc32 Hint] zint_telepen.pas(78): H2077 Value assigned to 'telepen' never used
[dcc32 Hint] zint_telepen.pas(113): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_postal.pas(76): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_postal.pas(118): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_postal.pas(149): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_postal.pas(191): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_postal.pas(223): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_postal.pas(340): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_postal.pas(392): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_postal.pas(445): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_postal.pas(497): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_postal.pas(533): H2077 Value assigned to 'error_number' never used
[dcc32 Hint] zint_postal.pas(532): H2077 Value assigned to 'inter_posn' never used
[dcc32 Warning] zint_postal.pas(597): W1036 Variable 'check_char' might not have been initialized
[dcc32 Hint] zint_imail.pas(337): H2077 Value assigned to 'error_number' never used
[dcc32 Warning] zint.pas(911): W1035 Return value of function 'SymbologyToInt' might be undefined
[dcc32 Warning] zint.pas(1002): W1035 Return value of function 'IntToSymbology' might be undefined

**Comment by landrix** [comment]
first work done, need some more investigation

**Comment by landrix** [comment]
done
