### ISSUE TITLE
Print a Code128 with small size

### ISSUE THREAD

**Issue by magnolima** [landrix/Zint-Barcode-Generator-for-Delphi#6]
Hi, based on the demo, I am trying to generate a small (3cm) barcode using Code 128. The full size is nice but I cannot read it when with that size. The spacing of 0 and 1 seems not to get correct, seems to cut, I dunno. What properties should I look at to fix it?
Thank you!

**Comment by landrix** [comment]
Which data you used to generate the barcode?

**Comment by magnolima** [comment]
Simple string like "ABCDEFGHI 12345678", if the image length is about
250px, ie., it prints nicely and the reader can scan. We need a size of
3.5cm.

An old Delphi shell application can print it but using PPLA commands.

Em ter, 23 de abr de 2019 16:14, Sven Harazim <notifications@github.com>
escreveu:
